-- Supabase Schema for A Guilda Badges

-- users
CREATE TABLE IF NOT EXISTS public.users (
  id TEXT PRIMARY KEY,
  discord_id TEXT UNIQUE NOT NULL,
  username TEXT NOT NULL,
  display_name TEXT,
  avatar TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- admins
CREATE TABLE IF NOT EXISTS public.admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  discord_id TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- badges
CREATE TABLE IF NOT EXISTS public.badges (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  image_url TEXT NOT NULL,
  category TEXT NOT NULL,
  rarity TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- codes
CREATE TABLE IF NOT EXISTS public.codes (
  id TEXT PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  badge_id TEXT NOT NULL REFERENCES public.badges(id),
  max_uses BIGINT,
  used_count BIGINT DEFAULT 0,
  expires_at TIMESTAMP WITH TIME ZONE,
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- user_badges
CREATE TABLE IF NOT EXISTS public.user_badges (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES public.users(id),
  badge_id TEXT NOT NULL REFERENCES public.badges(id),
  date_earned TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  source TEXT NOT NULL,
  UNIQUE(user_id, badge_id)
);

-- code_redemptions
CREATE TABLE IF NOT EXISTS public.code_redemptions (
  id TEXT PRIMARY KEY,
  code_id TEXT NOT NULL REFERENCES public.codes(id),
  user_id TEXT NOT NULL REFERENCES public.users(id),
  redeemed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(code_id, user_id)
);

-- security_logs
CREATE TABLE IF NOT EXISTS public.security_logs (
    id UUID PRIMARY KEY,
    user_id TEXT,
    ip_address TEXT,
    action TEXT,
    details JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Atomic Redemption Function (Hardened)
CREATE OR REPLACE FUNCTION redeem_code_atomic(
  p_code TEXT,
  p_user_id TEXT
) RETURNS JSONB 
LANGUAGE plpgsql
SECURITY DEFINER -- Required to update private 'codes' table
SET search_path = public
AS $$
DECLARE
  v_code_id TEXT;
  v_badge_id TEXT;
  v_max_uses INT;
  v_used_count INT;
  v_expires_at TIMESTAMP WITH TIME ZONE;
BEGIN
  -- 1. Security Check: Ensure caller is redeeming for themselves
  -- auth.uid() returns uuid, p_user_id is text in this schema
  IF auth.uid()::text IS DISTINCT FROM p_user_id THEN
    RETURN jsonb_build_object('success', false, 'error', 'UNAUTHORIZED');
  END IF;

  -- 2. Select and lock the code row
  SELECT id, badge_id, max_uses, used_count, expires_at 
  INTO v_code_id, v_badge_id, v_max_uses, v_used_count, v_expires_at
  FROM codes WHERE code = p_code FOR UPDATE;

  IF v_code_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'INVALID');
  END IF;

  IF v_expires_at IS NOT NULL AND v_expires_at < now() THEN
    RETURN jsonb_build_object('success', false, 'error', 'EXPIRED');
  END IF;

  IF v_max_uses IS NOT NULL AND v_used_count >= v_max_uses THEN
    RETURN jsonb_build_object('success', false, 'error', 'EXHAUSTED');
  END IF;

  -- 3. Check if user already owns the badge
  IF EXISTS (SELECT 1 FROM user_badges WHERE user_id = p_user_id AND badge_id = v_badge_id) THEN
    RETURN jsonb_build_object('success', false, 'error', 'OWNED');
  END IF;

  -- 4. Atomic Update and Grant
  UPDATE codes SET used_count = used_count + 1 WHERE id = v_code_id;

  INSERT INTO user_badges (id, user_id, badge_id, source) 
  VALUES (gen_random_uuid()::text, p_user_id, v_badge_id, 'code');
  
  INSERT INTO code_redemptions (id, code_id, user_id)
  VALUES (gen_random_uuid()::text, v_code_id, p_user_id);

  RETURN jsonb_build_object('success', true);
END;
$$;

-- Security Settings (RLS Enabled)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.code_redemptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.security_logs ENABLE ROW LEVEL SECURITY;

-- POLICIES

-- Badges: Public Read
CREATE POLICY "Badges are viewable by everyone" ON public.badges FOR SELECT USING (true);

-- Users: Public Read, Self Update
CREATE POLICY "Users are viewable by everyone" ON public.users FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON public.users FOR UPDATE USING (auth.uid()::text = id);
CREATE POLICY "Users can insert own profile" ON public.users FOR INSERT WITH CHECK (auth.uid()::text = id);

-- User Badges: Public Read
CREATE POLICY "User badges are viewable by everyone" ON public.user_badges FOR SELECT USING (true);

-- Admins: Public Read
CREATE POLICY "Admins are viewable by everyone" ON public.admins FOR SELECT USING (true);

-- Codes: Private (No public read, managed via RPC)
-- No policies = access denied for non-service-role users

-- Redemptions: Private
-- No policies = access denied

-- Logs: Private
-- No policies = access denied

